<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ModSyncServer</AssemblyName>
    <RootNamespace>ModSyncServer</RootNamespace>
    <Version>1.5.9.0</Version>
    <AssemblyVersion>1.5.9.0</AssemblyVersion>
    <FileVersion>1.5.9.0</FileVersion>
    <Company>open.mp</Company>
    <Product>open.mp ModSync CDN Server</Product>
    <Copyright>Copyright (C) 2026 open.mp &amp; eLdarqO</Copyright>
    <Authors>eLdarqO</Authors>
    <Description>Standalone High-Performance CDN Server for open.mp ModSync</Description>
  </PropertyGroup>

</Project>
